server:
  port: 8081
spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/corso
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic
      docente-service:
        connectTimeout: 3000
        readTimeout: 8000
        loggerLevel: full

# Logging per vedere le chiamate Feign
logging:
  level:
    com.example.demo.converter.DocenteClient: DEBUG
