server:
  port: 8082
spring:
  application:
    name: demo-client
  datasource:
    url: jdbc:postgresql://localhost:5432/corso
    username: postgres
    password: 1234567890
    driver-class-name: org.postgresql.Driver

